### ISSUE TITLE
[Theme Request] Kurumi Tokisaki from Date a Live

### ISSUE THREAD

**Issue by trueSamukinha** [doki-theme/doki-master-theme#190] opened 2022-07-16 22:38 UTC
## Who/What do you want to be featured?

Kurumi Tokisaki from Date a Live

### What do they look like?

![](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/8c2b2bff-e3ac-4ac3-a2df-e3aaf2b1eede/d80nivv-1dd1d66a-0443-4aa8-841b-23f4a8f9ccfc.png/v1/fill/w_1024,h_576,q_80,strp/kurumi_tokisaki__date_a_live__by_greenmapple17_d80nivv-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTc2IiwicGF0aCI6IlwvZlwvOGMyYjJiZmYtZTNhYy00YWMzLWEyZGYtZTNhYWYyYjFlZWRlXC9kODBuaXZ2LTFkZDFkNjZhLTA0NDMtNGFhOC04NDFiLTIzZjRhOGY5Y2NmYy5wbmciLCJ3aWR0aCI6Ijw9MTAyNCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.up-cRNLmtvcbnAw2DgQrWQjgG6vngDEIEpvrz8hNtIg)
---
![](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/16ae723c-b3b6-4cc1-b0bd-7f454d4d4e30/dcf3buk-7e909649-c326-4b6a-8382-2382cc1ed186.png/v1/fill/w_1024,h_576,q_80,strp/kurumi_tokisaki__date_a_live__minimalist_by_yusufnarendra_dcf3buk-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTc2IiwicGF0aCI6IlwvZlwvMTZhZTcyM2MtYjNiNi00Y2MxLWIwYmQtN2Y0NTRkNGQ0ZTMwXC9kY2YzYnVrLTdlOTA5NjQ5LWMzMjYtNGI2YS04MzgyLTIzODJjYzFlZDE4Ni5wbmciLCJ3aWR0aCI6Ijw9MTAyNCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.Y3SR6jB2HWiCIW6rSioNTRV_2pfHlqeAF2gVzE7omEw)
---
![](https://w0.peakpx.com/wallpaper/543/155/HD-wallpaper-kurumi-tokisaki-artwork-minimal-manga-date-a-live.jpg)
## What type of theme?

- [ ] Light Theme
- [x] Dark Theme

## Additional Information (Optional)

  
One of the best waifus! The color theme might look like rory mercury or rikka takanashi.

**Comment by Unthrottled** [comment] 2022-07-17 13:03
This is a duplicate of #164 , I'll close this, you can follow the original one for status updates, thanks! 👍 

She has a higher chance of making it it because I [already like her more](https://github.com/doki-theme/doki-master-theme/issues/76#issuecomment-833110903)

**Closed by Unthrottled** 2022-07-17 13:03 UTC
