### ISSUE TITLE
[Theme Request] Lain Iwakura

### ISSUE THREAD

**Issue by 0xlain** [doki-theme/doki-master-theme#165] opened 2022-04-26 07:42 UTC
## Who/What do you want to be featured?

[Lain Iwakura](https://sel.fandom.com/wiki/Lain_Iwakura)

### What do they look like?

![dhcvbgs](https://user-images.githubusercontent.com/92771507/165247156-eb0e6cbc-68c9-4555-8f4a-98ca70103128.jpg)
![image](https://user-images.githubusercontent.com/92771507/165247337-5f4d38e0-f8be-4315-aa5e-56d8f77f3d1f.png)
![dfb2f73b7aae41844e03a67a4e874bc3](https://user-images.githubusercontent.com/92771507/165247159-faeb482b-d587-4f1b-8467-6d13b932755c.gif)
![lain-dance](https://user-images.githubusercontent.com/92771507/165247134-f8bb5244-3c87-4954-bd6c-f60478b57c9e.gif)

## What type of theme?

- [ ] Light Theme
- [x] Dark Theme

## Additional Information (Optional)

🙏

**Comment by Unthrottled** [comment] 2022-04-26 10:28
Thanks for taking the time to make the request, however this is a duplicate of #146, I'm going to close this issue, feel free to follow the original.

**Closed by Unthrottled** 2022-04-26 10:28 UTC
