### ISSUE TITLE
[Theme Request] Raphtalia (Tate no Yuusha)

### ISSUE THREAD

**Issue by KevinV676** [doki-theme/doki-master-theme#122] opened 2021-09-25 23:11 UTC
## Who/What do you want to be featured?
Raphtalia from the anime and LN Tate no Yuusha 

### What do they look like?
Original Desing (Light Novel)
![Raphtalia_Light_Novel](https://user-images.githubusercontent.com/85595531/134788019-9519a4fd-50e9-4736-b5d7-7e7ac090a11a.png)
![raphtalia-11563760469uzjmrwzk3s](https://user-images.githubusercontent.com/85595531/134788023-e3e7c245-5578-47dd-b365-f1f39e6e9cc9.png)
Fanarts
(This please the background)
![dfgdf](https://user-images.githubusercontent.com/85595531/134787926-b3610072-3637-4485-a078-4a354fb27942.jpg) 
![illust_74282237_20190807_214308](https://user-images.githubusercontent.com/85595531/134787942-341d4eb6-d5a9-4383-b1aa-e8830cc3208c.jpg)
![illust_74582642_20190506_210003](https://user-images.githubusercontent.com/85595531/134787954-0b63b153-c745-4c99-b7fb-80b136d887f4.jpg)

## What type of theme?

- [ ] Light Theme
- [ x] Dark Theme

## Additional Information (Optional)

Raphtalia is a character from Tate no Yuusha, rather, she is the BEST WAIFU, and that she is added to the Doki would be a new way for more people to know her and admire the beauty that she is.

thanks for reading this, and sorry for the inconvenience.

**Comment by Unthrottled** [comment] 2021-09-26 01:11
Hey Fam! Thanks for the suggestion, pretty sure this a duplicate of #84, you can track the status on that issue. Thanks for the interest and taking the time to submit this though!

**Closed by Unthrottled** 2021-09-26 01:11 UTC
Labels: duplicate
