### ISSUE TITLE
[Theme Request] Itachi Uchiha

### ISSUE THREAD

**Issue by SilverDeus** [doki-theme/doki-master-theme#223] opened 2023-02-17 11:27 UTC
Who/What do you want to be featured?

Kid and adult Itachi Uchiha from Naruto Shippuden

What do they look like?

Kid :   https://www.pinterest.com/pin/94927504635407610/
kid: https://www.pinterest.fr/pin/833799318526191778/
kid: https://www.pinterest.fr/pin/174021973093644740/
kid: https://www.pinterest.fr/pin/654359020879829329/
kid: https://www.pinterest.fr/pin/245657354666566614/

adult: https://www.pinterest.fr/pin/750623462874885837/
adult: https://www.pinterest.fr/pin/799107527645261976/
adult: https://www.pinterest.fr/pin/71846556546015812/
adult: https://www.pinterest.fr/pin/1142858842915841377/
adult: https://www.pinterest.fr/pin/624733779533038621/
adult: https://www.pinterest.fr/pin/793829871835706996/
adult: https://www.pinterest.fr/pin/245657354666519674/
adult: https://www.pinterest.fr/pin/896357132058902990/
adult: https://www.pinterest.fr/pin/44543483808585646/
adult: https://www.pinterest.fr/pin/44543483808585646/
adult: https://www.pinterest.fr/pin/673921531755711089/
adult: https://www.pinterest.fr/pin/374713631501084460/
adult: https://www.pinterest.fr/pin/374713631501084460/
adult: https://www.pinterest.fr/pin/245657354666665042/
adult: https://www.pinterest.fr/pin/245657354666566614/

What type of theme?

- [ x] Light Theme
- [ x] Dark Theme

Additional Information (Optional)

Itachi is one of the best, coolest and most devoted shinobi in anime

**Comment by Unthrottled** [comment] 2023-02-19 16:23
Duplicate of #204

**Closed by Unthrottled** 2023-02-19 16:23 UTC
Labels: duplicate
